package connecthub.backend;

public interface Constants {

    String USER_FILENAME = "USERS_DATABASE";
    String REGEX = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    String POST_FILENAME = "POST_DATABASE";
    String STORY_FILENAME = "STORY_DATABASE";
    String DEFAULT_PROFILE= "defaultprofile";
    String RELATIONS_DATABASE = "relationDatabase";
    String FRIENDS_REQUEST_DATABASE = "friend_requests";
    String GROUP_FILENAME = "GROUP_DATABASE";
    String GROUP_ADDITION_NOTIFICATION_DATABASE = "GROUP_ADDITION_NOTIFICATIONS_DATABASE";
    String GROUP_STATUS_NOTIFICATION_DATABASE = "GROUP_STATUS_NOTIFICATIONS_DATABASE";
    String GROUP_POST_NOTIFICATION_DATABASE = "GROUP_POST_NOTIFICATIONS_DATABASE";
    String FRIEND_REQUEST_NOTIFICATION_DATABASE = "FRIEND_REQUEST_NOTIFICATIONS_DATABASE";
    String GROUP_REQUESTS_FILENAME = "GROUP_REQUESTS_DATABASE";
    String GROUP_REQUEST_NOTIFICATION_DATABASE = "GROUP_REQUEST_NOTIFICATION_DATABASE";
}
